<?php
return [
    1 => "Receita",
    2 => "Aluguel",
    3 => "Financiamento",
    4 => "Condomínio",
    5 => "IPTU",
    6 => "Água",
    7 => "Luz",
    8 => "Gás",
    9 => "Combustível",
    10 => "Transporte público",
    11 => "Manutenção de veículo",
    12 => "Seguro de carro",
    13 => "Estacionamento",
    14 => "Supermercado",
    15 => "Restaurantes",
    16 => "Lanches e delivery",
    17 => "Plano de saúde",
    18 => "Consultas médicas",
    19 => "Medicamentos",
    20 => "Exames",
    21 => "Mensalidade escolar",
    22 => "Cursos e treinamentos",
    23 => "Livros e material escolar",
    24 => "Cinema",
    25 => "Viagens",
    26 => "Assinaturas de streaming",
    27 => "Atividades recreativas",
    28 => "Internet",
    29 => "Celular",
    30 => "TV a cabo",
    31 => "Limpeza",
    32 => "Cuidados pessoais",
    33 => "Impostos sobre a renda",
    34 => "Taxas bancárias",
    35 => "Multas",
    36 => "Compras de vestuário",
    37 => "Calçados",
    38 => "Acessórios",
    39 => "Seguro de vida",
    40 => "Seguro residencial",
    41 => "Seguro de carro",
    42 => "Contribuições para poupança",
    43 => "Investimentos",
    44 => "Outros"
];

