<?php
// Em config/categories.php
return [
    1 => "Aluguel",
    2 => "Financiamento",
    3 => "Condomínio",
    4 => "IPTU",
    5 => "Água",
    6 => "Luz",
    7 => "Gás",
    8 => "Combustível",
    9 => "Transporte público",
    10 => "Manutenção de veículo",
    11 => "Seguro de carro",
    12 => "Estacionamento",
    13 => "Supermercado",
    14 => "Restaurantes",
    15 => "Lanches e delivery",
    16 => "Plano de saúde",
    17 => "Consultas médicas",
    18 => "Medicamentos",
    19 => "Exames",
    20 => "Mensalidade escolar",
    21 => "Cursos e treinamentos",
    22 => "Livros e material escolar",
    23 => "Cinema",
    24 => "Viagens",
    25 => "Assinaturas de streaming",
    26 => "Atividades recreativas",
    27 => "Internet",
    28 => "Celular",
    29 => "TV a cabo",
    30 => "Limpeza",
    31 => "Cuidados pessoais",
    32 => "Impostos sobre a renda",
    33 => "Taxas bancárias",
    34 => "Multas",
    35 => "Compras de vestuário",
    36 => "Calçados",
    37 => "Acessórios",
    38 => "Seguro de vida",
    39 => "Seguro residencial",
    40 => "Seguro de carro",
    41 => "Contribuições para poupança",
    42 => "Investimentos",
    43 => "Outros"
];
